Mining System
dxura/darkrp pull request #29
Opened 2024-09-14 16:32 UTC by yagizakgun

Mining System first version
![eyGfZADKiB](https://github.com/user-attachments/assets/5036e818-2265-4df1-8772-6120096d6c4e)

2024-09-14 16:38 UTC, yagizakgun reviewed
-Delete Atm system files

2024-09-16 14:24 UTC, yagizakgun commented
Ore dealer's code is finished for now. 
**What I plan to add; pickaxe viewmodel and wordmodels.**

**Features that work now;**
-Respawning of the mined rock after 10 seconds
-You get 3 ore from the rock and when you take it to the vendor and sell it, you get 300 dollars.
-Only miners can open the vendor
-Rock properties can be set with the .rck resource file

2024-09-16 14:37 UTC, B0zy commented
Curious where's the Rock model from?

2024-09-16 14:39 UTC, yagizakgun commented
https://www.cgtrader.com/free-3d-models/scanned/various/rock-pack-vol-2-free

2024-09-16 14:44 UTC, B0zy commented
👍 Was just curious. Its in our best interest to keep reference to models from online for licenses and whatnot ( Just a opinion I don't rlly have a say )

2024-09-17 12:38 UTC, jusvit commented
Could you compress the pngs and textures, they're quite large for a rock.

Use https://saerasoft.com/caesium quite nifty

2024-09-17 13:16 UTC, yagizakgun commented
[compressed pngs and textures](https://github.com/dxura/darkrp/pull/29/commits/f59f23cce8fca7dab9d5d4b12fc1023096c53a9e)

2024-09-17 13:18 UTC, jusvit requested changes

2024-09-17 13:18 UTC, jusvit commented on Code/Gameplay/Equipment/EquipmentData.cs
> +	[Category( "Mining" )] public float PickaxeDamage { get; set; }
Doesn't belong here, don't add specific info to equipment. 

I suggest you look at how melee weapons work. You should create a component that will hold pickaxe-specific logic (Which you can set tiers on the prefabs)

2024-09-17 13:18 UTC, jusvit commented on Code/UI/Entities/Mining/OreVendorMenu.razor.scss
In future don't use PX, it isn't scalable, prefer em and % for margins/paddings

2024-09-17 13:18 UTC, jusvit commented on Code/Player/State/PlayerState.Money.cs
> +
Move this to PlayerState.Inventory even if it is only for rocks atm.

I don't think they should be persisted, they should be sold within the play session. - Open to correction

Also maybe drop rocks/remove rocks when you die?

2024-09-17 13:18 UTC, jusvit commented on Code/Gameplay/Equipment/Mining/Pickaxe.cs
> +    [Property] private float InteractRange { get; set; } = 60f;
This is where you could set the tier damage (Kinda like printers), so you can remove the variable from the equipmentData

2024-09-17 13:18 UTC, jusvit commented on Code/Gameplay/Entities/Mining/Rock1Entity.cs
Also can you explain the networking behind this? Each rock seems to only be client-side, there's no shared game state?

2024-11-12 12:34 UTC, jusvit commented
Closed due to inactivity

2024-11-12 12:34 UTC, closed without merging