light prefab port + map work
dxura/darkrp pull request #34
Opened 2024-09-15 11:53 UTC by sousou63

- Port of the light prefab
- Light prefab placement on the map
- Atm placements
- Fence placements

2024-09-15 22:05 UTC, jusvit commented
Shouldn't those type of lights be baked into the map not placed with components for performance reasons.

2024-09-15 22:06 UTC, jusvit requested changes

2024-09-15 22:06 UTC, jusvit commented on Assets/prefabs/player/player.prefab
> +        "StepHeight": 18,
Wasn't this just set to fix climbing stairs?

2024-09-15 22:39 UTC, sousou63 commented on Assets/prefabs/player/player.prefab
> +        "StepHeight": 18,
This value is the default one and it work the best, before it was set to something like 1.1

2024-09-15 22:45 UTC, sousou63 commented
No worries I've took the time to optimize them ( no impact on performances at all ) and are easy to place because of the prefab. This is not really a final solution more like a temporary solution to the map lightning meanwhile we get more comfortable with hammer. facepunch also want to get rid of hammer in the future to replace it with the scene so we will see.

2024-09-16 07:20 UTC, jusvit approved these changes

2024-09-16 07:20 UTC, merged